[2023-09-11 12:02:52,794] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: listing_4_20.write_to_postgres scheduled__2023-09-11T08:00:00+00:00 [queued]>
[2023-09-11 12:02:52,803] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: listing_4_20.write_to_postgres scheduled__2023-09-11T08:00:00+00:00 [queued]>
[2023-09-11 12:02:52,803] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 12:02:52,803] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 12:02:52,804] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 12:02:52,819] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): write_to_postgres> on 2023-09-11 08:00:00+00:00
[2023-09-11 12:02:52,824] {standard_task_runner.py:52} INFO - Started process 1485 to run task
[2023-09-11 12:02:52,827] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_20', 'write_to_postgres', 'scheduled__2023-09-11T08:00:00+00:00', '--job-id', '540', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_20.py', '--cfg-path', '/tmp/tmp3zk71qsl', '--error-file', '/tmp/tmp_2qjlu6e']
[2023-09-11 12:02:52,827] {standard_task_runner.py:80} INFO - Job 540: Subtask write_to_postgres
[2023-09-11 12:02:52,888] {task_command.py:371} INFO - Running <TaskInstance: listing_4_20.write_to_postgres scheduled__2023-09-11T08:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 12:02:53,025] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_20
AIRFLOW_CTX_TASK_ID=write_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-09-11T08:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-11T08:00:00+00:00
[2023-09-11 12:02:53,049] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 204, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_postgres` isn't defined
[2023-09-11 12:02:53,053] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=listing_4_20, task_id=write_to_postgres, execution_date=20230911T080000, start_date=20230911T120252, end_date=20230911T120253
[2023-09-11 12:02:53,063] {standard_task_runner.py:97} ERROR - Failed to execute job 540 for task write_to_postgres (The conn_id `my_postgres` isn't defined; 1485)
[2023-09-11 12:02:53,079] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-11 12:02:53,107] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
