[2023-09-11 22:10:38,923] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: BigTechCompanyCount.get_data scheduled__2023-09-11T20:00:00+00:00 [queued]>
[2023-09-11 22:10:38,940] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: BigTechCompanyCount.get_data scheduled__2023-09-11T20:00:00+00:00 [queued]>
[2023-09-11 22:10:38,940] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 22:10:38,941] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 22:10:38,941] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 22:10:38,965] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-09-11 20:00:00+00:00
[2023-09-11 22:10:38,972] {standard_task_runner.py:52} INFO - Started process 16081 to run task
[2023-09-11 22:10:38,977] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'BigTechCompanyCount', 'get_data', 'scheduled__2023-09-11T20:00:00+00:00', '--job-id', '882', '--raw', '--subdir', 'DAGS_FOLDER/BigTechCompanyCount.py', '--cfg-path', '/tmp/tmpt2ly2b83', '--error-file', '/tmp/tmpb6buxh5_']
[2023-09-11 22:10:38,977] {standard_task_runner.py:80} INFO - Job 882: Subtask get_data
[2023-09-11 22:10:39,072] {task_command.py:371} INFO - Running <TaskInstance: BigTechCompanyCount.get_data scheduled__2023-09-11T20:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 22:10:39,119] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-11 22:10:39,159] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=BigTechCompanyCount
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-11T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-11T20:00:00+00:00
[2023-09-11 22:10:39,882] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/BigTechCompanyCount.py", line 21, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-09-11 22:10:39,893] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=BigTechCompanyCount, task_id=get_data, execution_date=20230911T200000, start_date=20230911T221038, end_date=20230911T221039
[2023-09-11 22:10:39,907] {standard_task_runner.py:97} ERROR - Failed to execute job 882 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 16081)
[2023-09-11 22:10:39,952] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-11 22:10:40,169] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
