[2023-09-09 15:19:27,232] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures manual__2023-09-09T15:19:22.725794+00:00 [queued]>
[2023-09-09 15:19:27,243] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures manual__2023-09-09T15:19:22.725794+00:00 [queued]>
[2023-09-09 15:19:27,243] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-09 15:19:27,243] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-09 15:19:27,243] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-09 15:19:27,257] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_pictures> on 2023-09-09 15:19:22.725794+00:00
[2023-09-09 15:19:27,260] {standard_task_runner.py:52} INFO - Started process 18597 to run task
[2023-09-09 15:19:27,263] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'manual__2023-09-09T15:19:22.725794+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/download_rocket_launches.py', '--cfg-path', '/tmp/tmpnctf0bwe', '--error-file', '/tmp/tmp1f85w_5m']
[2023-09-09 15:19:27,263] {standard_task_runner.py:80} INFO - Job 51: Subtask get_pictures
[2023-09-09 15:19:27,382] {task_command.py:371} INFO - Running <TaskInstance: download_rocket_launches.get_pictures manual__2023-09-09T15:19:22.725794+00:00 [running]> on host b18943745c0d
[2023-09-09 15:19:27,454] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2023-09-09T15:19:22.725794+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-09T15:19:22.725794+00:00
[2023-09-09 15:19:27,455] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_rocket_launches.py", line 37, in _get_pictures
    abs_images_dir = os.path.abspath(image_urls)
  File "/usr/local/lib/python3.7/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not list
[2023-09-09 15:19:27,465] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20230909T151922, start_date=20230909T151927, end_date=20230909T151927
[2023-09-09 15:19:27,477] {standard_task_runner.py:97} ERROR - Failed to execute job 51 for task get_pictures (expected str, bytes or os.PathLike object, not list; 18597)
[2023-09-09 15:19:27,516] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-09 15:19:27,558] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
