[2023-09-11 06:30:52,244] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T20:00:00+00:00 [queued]>
[2023-09-11 06:30:52,292] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T20:00:00+00:00 [queued]>
[2023-09-11 06:30:52,294] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:30:52,296] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 06:30:52,297] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:30:52,469] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-09-10 20:00:00+00:00
[2023-09-11 06:30:52,531] {standard_task_runner.py:52} INFO - Started process 158 to run task
[2023-09-11 06:30:52,577] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Examine_Templet_Value', 'get_data', 'scheduled__2023-09-10T20:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/Examine_Templet_Value.py', '--cfg-path', '/tmp/tmprfcq5j5v', '--error-file', '/tmp/tmp9wt82dm7']
[2023-09-11 06:30:52,617] {standard_task_runner.py:80} INFO - Job 160: Subtask get_data
[2023-09-11 06:30:53,572] {task_command.py:371} INFO - Running <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T20:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 06:30:54,023] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-11 06:30:54,546] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Examine_Templet_Value
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-10T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-10T20:00:00+00:00
[2023-09-11 06:30:55,272] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Examine_Templet_Value.py", line 19, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-09-11 06:30:55,434] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Examine_Templet_Value, task_id=get_data, execution_date=20230910T200000, start_date=20230911T063052, end_date=20230911T063055
[2023-09-11 06:30:55,626] {standard_task_runner.py:97} ERROR - Failed to execute job 160 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 158)
[2023-09-11 06:30:55,692] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-11 06:30:55,985] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-11 06:48:55,773] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T20:00:00+00:00 [queued]>
[2023-09-11 06:48:55,850] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T20:00:00+00:00 [queued]>
[2023-09-11 06:48:55,850] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:48:55,851] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 06:48:55,851] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:48:55,981] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-09-10 20:00:00+00:00
[2023-09-11 06:48:56,013] {standard_task_runner.py:52} INFO - Started process 970 to run task
[2023-09-11 06:48:56,028] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Examine_Templet_Value', 'get_data', 'scheduled__2023-09-10T20:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/Examine_Templet_Value.py', '--cfg-path', '/tmp/tmpyqkdizoz', '--error-file', '/tmp/tmpw7rfuge0']
[2023-09-11 06:48:56,029] {standard_task_runner.py:80} INFO - Job 192: Subtask get_data
[2023-09-11 06:48:56,360] {task_command.py:371} INFO - Running <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T20:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 06:48:56,479] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-11 06:48:56,704] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Examine_Templet_Value
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-10T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-10T20:00:00+00:00
[2023-09-11 06:48:57,503] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Examine_Templet_Value.py", line 19, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-09-11 06:48:57,534] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Examine_Templet_Value, task_id=get_data, execution_date=20230910T200000, start_date=20230911T064855, end_date=20230911T064857
[2023-09-11 06:48:57,588] {standard_task_runner.py:97} ERROR - Failed to execute job 192 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 970)
[2023-09-11 06:48:57,634] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-11 06:48:57,760] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
