[2023-09-12 04:45:55,054] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: CallPostgreOperator.get_data scheduled__2023-09-11T00:00:00+00:00 [queued]>
[2023-09-12 04:45:55,063] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: CallPostgreOperator.get_data scheduled__2023-09-11T00:00:00+00:00 [queued]>
[2023-09-12 04:45:55,064] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-12 04:45:55,064] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-09-12 04:45:55,064] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-12 04:45:55,077] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-09-11 00:00:00+00:00
[2023-09-12 04:45:55,081] {standard_task_runner.py:52} INFO - Started process 722 to run task
[2023-09-12 04:45:55,084] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'CallPostgreOperator', 'get_data', 'scheduled__2023-09-11T00:00:00+00:00', '--job-id', '954', '--raw', '--subdir', 'DAGS_FOLDER/CallPostgreOperator.py', '--cfg-path', '/tmp/tmp0igt4wl2', '--error-file', '/tmp/tmpg5mwrnez']
[2023-09-12 04:45:55,084] {standard_task_runner.py:80} INFO - Job 954: Subtask get_data
[2023-09-12 04:45:55,150] {task_command.py:371} INFO - Running <TaskInstance: CallPostgreOperator.get_data scheduled__2023-09-11T00:00:00+00:00 [running]> on host b18943745c0d
[2023-09-12 04:45:55,187] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-12 04:45:55,222] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=CallPostgreOperator
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-11T00:00:00+00:00
[2023-09-12 04:48:39,700] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/CallPostgreOperator.py", line 27, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 1294005 out of 40934870 bytes>
[2023-09-12 04:48:39,712] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=CallPostgreOperator, task_id=get_data, execution_date=20230911T000000, start_date=20230912T044555, end_date=20230912T044839
[2023-09-12 04:48:39,724] {standard_task_runner.py:97} ERROR - Failed to execute job 954 for task get_data (<urlopen error retrieval incomplete: got only 1294005 out of 40934870 bytes>; 722)
[2023-09-12 04:48:39,752] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-12 04:48:39,787] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
