[2023-09-11 22:10:24,165] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: params_test_with_wikimedia.get_data scheduled__2023-09-11T21:00:00+00:00 [queued]>
[2023-09-11 22:10:24,454] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: params_test_with_wikimedia.get_data scheduled__2023-09-11T21:00:00+00:00 [queued]>
[2023-09-11 22:10:24,454] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 22:10:24,454] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 22:10:24,454] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 22:10:24,533] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-09-11 21:00:00+00:00
[2023-09-11 22:10:24,565] {standard_task_runner.py:52} INFO - Started process 16056 to run task
[2023-09-11 22:10:24,624] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'params_test_with_wikimedia', 'get_data', 'scheduled__2023-09-11T21:00:00+00:00', '--job-id', '874', '--raw', '--subdir', 'DAGS_FOLDER/params_test_with_wikimedia.py', '--cfg-path', '/tmp/tmp_9ajyjnf', '--error-file', '/tmp/tmpr9s4kkq2']
[2023-09-11 22:10:24,637] {standard_task_runner.py:80} INFO - Job 874: Subtask get_data
[2023-09-11 22:10:25,407] {task_command.py:371} INFO - Running <TaskInstance: params_test_with_wikimedia.get_data scheduled__2023-09-11T21:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 22:10:25,688] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-11 22:10:25,992] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=params_test_with_wikimedia
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-11T21:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-11T21:00:00+00:00
[2023-09-11 22:10:26,004] {logging_mixin.py:115} INFO - 현재 전달된 url은 https://dumps.wikimedia.org/other/pageviews/2023/2023-09/pageviews-20230911-200000.gz 이다.
[2023-09-11 22:10:28,409] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/params_test_with_wikimedia.py", line 33, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-09-11 22:10:28,449] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=params_test_with_wikimedia, task_id=get_data, execution_date=20230911T210000, start_date=20230911T221024, end_date=20230911T221028
[2023-09-11 22:10:28,474] {standard_task_runner.py:97} ERROR - Failed to execute job 874 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 16056)
[2023-09-11 22:10:28,512] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-11 22:10:28,581] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
