[2023-09-11 06:30:44,779] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T16:00:00+00:00 [queued]>
[2023-09-11 06:30:44,816] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T16:00:00+00:00 [queued]>
[2023-09-11 06:30:44,817] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:30:44,818] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 06:30:44,819] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:30:44,876] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-09-10 16:00:00+00:00
[2023-09-11 06:30:44,890] {standard_task_runner.py:52} INFO - Started process 143 to run task
[2023-09-11 06:30:44,900] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Examine_Templet_Value', 'get_data', 'scheduled__2023-09-10T16:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/Examine_Templet_Value.py', '--cfg-path', '/tmp/tmplpknldza', '--error-file', '/tmp/tmp6h2o2wj8']
[2023-09-11 06:30:44,901] {standard_task_runner.py:80} INFO - Job 156: Subtask get_data
[2023-09-11 06:30:45,104] {task_command.py:371} INFO - Running <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T16:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 06:30:45,219] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-11 06:30:45,408] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Examine_Templet_Value
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-10T16:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-10T16:00:00+00:00
[2023-09-11 06:30:46,167] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Examine_Templet_Value.py", line 19, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-09-11 06:30:46,305] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Examine_Templet_Value, task_id=get_data, execution_date=20230910T160000, start_date=20230911T063044, end_date=20230911T063046
[2023-09-11 06:30:46,534] {standard_task_runner.py:97} ERROR - Failed to execute job 156 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 143)
[2023-09-11 06:30:46,603] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-11 06:30:46,781] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-11 06:48:51,498] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T16:00:00+00:00 [queued]>
[2023-09-11 06:48:51,631] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T16:00:00+00:00 [queued]>
[2023-09-11 06:48:51,664] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:48:51,664] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 06:48:51,665] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:48:51,823] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-09-10 16:00:00+00:00
[2023-09-11 06:48:51,866] {standard_task_runner.py:52} INFO - Started process 963 to run task
[2023-09-11 06:48:51,896] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Examine_Templet_Value', 'get_data', 'scheduled__2023-09-10T16:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/Examine_Templet_Value.py', '--cfg-path', '/tmp/tmpjdx2vbu6', '--error-file', '/tmp/tmpzmq8pet7']
[2023-09-11 06:48:51,898] {standard_task_runner.py:80} INFO - Job 188: Subtask get_data
[2023-09-11 06:48:52,631] {task_command.py:371} INFO - Running <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-10T16:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 06:48:52,887] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-11 06:48:53,229] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Examine_Templet_Value
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-10T16:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-10T16:00:00+00:00
[2023-09-11 06:48:54,186] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Examine_Templet_Value.py", line 19, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-09-11 06:48:54,245] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Examine_Templet_Value, task_id=get_data, execution_date=20230910T160000, start_date=20230911T064851, end_date=20230911T064854
[2023-09-11 06:48:54,466] {standard_task_runner.py:97} ERROR - Failed to execute job 188 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 963)
[2023-09-11 06:48:54,548] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-11 06:48:54,894] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
