[2023-09-11 06:30:57,614] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-11T02:00:00+00:00 [queued]>
[2023-09-11 06:30:57,663] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-11T02:00:00+00:00 [queued]>
[2023-09-11 06:30:57,663] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:30:57,664] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 06:30:57,664] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:30:57,749] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-09-11 02:00:00+00:00
[2023-09-11 06:30:57,763] {standard_task_runner.py:52} INFO - Started process 171 to run task
[2023-09-11 06:30:57,781] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Examine_Templet_Value', 'get_data', 'scheduled__2023-09-11T02:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/Examine_Templet_Value.py', '--cfg-path', '/tmp/tmpary7iqgw', '--error-file', '/tmp/tmpvuph3gji']
[2023-09-11 06:30:57,781] {standard_task_runner.py:80} INFO - Job 166: Subtask get_data
[2023-09-11 06:30:58,027] {task_command.py:371} INFO - Running <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-11T02:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 06:30:58,191] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-11 06:30:58,396] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Examine_Templet_Value
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-11T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-11T02:00:00+00:00
[2023-09-11 06:31:08,734] {python.py:173} INFO - Done. Returned value was: None
[2023-09-11 06:31:08,761] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Examine_Templet_Value, task_id=get_data, execution_date=20230911T020000, start_date=20230911T063057, end_date=20230911T063108
[2023-09-11 06:31:08,804] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-09-11 06:31:08,847] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-11 06:49:19,574] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-11T02:00:00+00:00 [queued]>
[2023-09-11 06:49:19,620] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-11T02:00:00+00:00 [queued]>
[2023-09-11 06:49:19,620] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:49:19,621] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 06:49:19,621] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 06:49:19,654] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-09-11 02:00:00+00:00
[2023-09-11 06:49:19,678] {standard_task_runner.py:52} INFO - Started process 1002 to run task
[2023-09-11 06:49:19,692] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Examine_Templet_Value', 'get_data', 'scheduled__2023-09-11T02:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/Examine_Templet_Value.py', '--cfg-path', '/tmp/tmp2y05_qa6', '--error-file', '/tmp/tmpo559dbj4']
[2023-09-11 06:49:19,693] {standard_task_runner.py:80} INFO - Job 198: Subtask get_data
[2023-09-11 06:49:19,913] {task_command.py:371} INFO - Running <TaskInstance: Examine_Templet_Value.get_data scheduled__2023-09-11T02:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 06:49:20,039] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-11 06:49:20,194] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Examine_Templet_Value
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-11T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-11T02:00:00+00:00
[2023-09-11 06:49:21,018] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Examine_Templet_Value.py", line 19, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-09-11 06:49:21,049] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Examine_Templet_Value, task_id=get_data, execution_date=20230911T020000, start_date=20230911T064919, end_date=20230911T064921
[2023-09-11 06:49:21,122] {standard_task_runner.py:97} ERROR - Failed to execute job 198 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 1002)
[2023-09-11 06:49:21,175] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-11 06:49:21,285] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
